<?php   
    $view = $this->getView(); 
    $reviews = $view['data_review']['Feedbacks'];
?>

<div class="box-collateral box-reviews" id="customer-reviews">

    <h2><?php echo __('Feedaty Reviews') ?></h2>

    <dl>    

        <?php foreach ($reviews as $k => $r) { ?>
        <!-- start here -->
    
        <div >

            <div class="review-ratings" >

                <meta content="<?php echo ($r['ProductRating']);?>" />

            </div>

            <div class="rating-summary item" >
                <div class="rating-result">
                    <span style="width:<?php echo ($r['ProductRating'])*20;?>%;"></span>
                </div>
            </div>

            <div class="review-content" >
                <?php echo $r['ProductReview']; ?>
            </div>

        </div>
    
        <!-- end here -->
        <?php } ?>
    </dl>
    <?php echo $view['link']; ?>

</div>