<?php
/* @var $block \Feedaty\Badge\Block\ProductSnippet */
$store_scope = \Magento\Store\Model\ScopeInterface::SCOPE_STORE;

/**
 * Get Product
 */
$product = $block->getProduct();

/**
 * Get merchantId
 */
$merchant = $block->getFeedatyCode();

/**
 * Get Base domain URL
 */
$baseUrl = $this->getBaseUrl();

/**
 * Get media URL
 */
$mediaUrl = $this->getMediaUrl();

/**
 * If product exist
 */
if ($product !== null) {

    $productId = $product->getId();

    /**
     * Product Reviews data
     */
    $reviews = $block->getProductReviews($productId);

}
?>

<?php if (!empty($reviews->getData())) : ?>


    <?php

    /**
     * Product name
     */
    $productName = $block->getProductName();

    /**
     * Product URL
     */
    $productUrl = $block->getProductUrl();

    /**
     * Product Stock
     */
    $productIsSalable = $block->getProductIsSalable() === true ? "https://schema.org/InStock" : "https://schema.org/OutOfStock";

    /**
     * Product Currency Code
     */
    $currencyCode = $block->getCurrencyCode();

    /**
     * Product Final Price
     */
    $productFinalPrice = $block->getProductFinalPrice();

    /**
     * Product sku
     */
    $productSku = $block->getProductSku();


    /**
     * Product Desc
     */

    $productDescription = $block->getProductDescription() !== null ? strip_tags($block->getProductDescription()) : '';

    /**
     * Merchant Code
     */
    $merchantName = $block->getStoreName();


    $reviewsJson = array();


    /**
     * Get all reviews
     */
    foreach ($reviews as $item) {

        /**
         * Product rating
         */
        $countRatings = count($item->getRatingVotes()) > 0 ? count($item->getRatingVotes()) : 1;
        $allRatings = 0;
        foreach ($item->getRatingVotes() as $vote) {
            $allRatings = $allRatings + $vote->getPercent();
        }
        $allRatingsAvg = $allRatings / $countRatings;


        $itemRatingValue =  $allRatingsAvg.'%';

        /**
         * Review Desc Details
         */
        $itemReview = $item->getDetail();

        /**
         * Review Date
         */
        $itemReviewDate = date("Y-m-d", strtotime($item->getCreatedAt()));

        /**
         * Review Customer Name
         */
        $itemNickname = $item->getNickname();

        $reviewsJson[] =
            array(
                "@type" => "Review",
                "reviewRating" => [
                    "@type" => "Rating",
                    "ratingValue" => "$itemRatingValue"
                ],
                "name" => "$productName",
                "datePublished" => "$itemReviewDate",
                "author" => [
                    "@type" => "Organization",
                    "name" => "$itemNickname"
                ],
                "reviewBody" => "$itemReview",
                "publisher" => [
                    "@type" => "Organization",
                    "name" => "$merchantName"
                ]
            );
    }

    /**
     * Rating Value
     */
    $ratingValue = $block->getRatingSummary($product).'%';


    /**
     * Total product feedback
     */
    $ratingsCount = $reviews->count();

    $reviewCount = $reviews->count();


    /**
     * Get Aggregate Rating and Product info
     */
    $snippet = array(
        "@context" => "http://schema.org/",
        "@type" => "Product",
        "description" => $productDescription,
        "sku" => $productSku,
        "image" => $mediaUrl . 'catalog/product' . $block->getProductImage(),
        "name" => $productName,
        "offers" => [
            "@type" => "Offer",
            "url" => $productUrl,
            "priceCurrency" => $currencyCode,
            "price" => $productFinalPrice,
            "availability" => $productIsSalable
        ],
        "aggregateRating" => [
            "@type" => "AggregateRating",
            "ratingValue" => $ratingValue,
            "ratingCount" => $ratingsCount
        ],
        "reviewCount" => $reviewCount,
        "review" => $reviewsJson
    );

    ?>

    <?php echo '<script type="application/ld+json">' . json_encode($snippet) . '</script>'; ?>

<?php endif; ?>
