<?php
/* @var $block Feedaty\Badge\Block\Widget\ProductBadge */

?>

<?php

$zoorate_env = "widget.zoorate.com";
/*
 * Merchant Code
 */
$merchant =  $block->getFeedatyCode();

$data = $block->getFeedatyData($merchant);

$badge_style = $block->getData('style');
$variant = $block->getData('variant');
$rvlang = $block->getData('rvlang');
$guilang = $block->getData('guilang');

$rvlang = $rvlang ? $rvlang : "all";

$guilang = $guilang ? $guilang : "it-IT";

$product = $block->getCurrentProduct();

if (!empty($product)) {

    $productId = $product->getId();

    if (count($data) > 0) {
        $ver = $block->getExtensionVersion();

        if (array_key_exists($badge_style, $data)) {
            $widget = $data[$badge_style];

            if (array_key_exists($variant, $widget["variants"])) {

                $name = $widget["name"];

                $variant = $widget["variants"][$variant];

                $rvlang = $rvlang ? $rvlang : "all";

                $guilang = $guilang ? $guilang : "it-IT";

                $widget['html'] = str_replace("ZOORATE_SERVER", $zoorate_env, $widget['html']);
                $widget['html'] = str_replace("VARIANT", $variant, $widget['html']);
                $widget['html'] = str_replace("GUI_LANG", $guilang, $widget['html']);
                $widget['html'] = str_replace("REV_LANG", $rvlang, $widget['html']);
                $widget['html'] = str_replace("SKU", $productId, $widget['html']);

                $element = htmlspecialchars_decode($widget["html"]);

                echo "<!-- PlPMa " . $ver[0] . " -->" . $element;
            }
        }
    }
}


?>
